import type { TopicManifest, TopicConfig } from '../types/topic';

const topicLoaders: Record<string, () => Promise<{ default: TopicConfig }>> = {
  'network-simulation': () => import('./network-simulation/config'),
  'prod-architecture': () => import('./prod-architecture/config'),
  'security-groups': () => import('./security-groups/config'),
  'ssm-port-forwarding': () => import('./ssm-port-forwarding/config'),
  'secrets-injection': () => import('./secrets-injection/config'),
  'egress-nat-vs-vpce': () => import('./egress-nat-vs-vpce/config'),
  'multi-az-failover': () => import('./multi-az-failover/config'),
  'ecs-scaling': () => import('./ecs-scaling/config'),
  'nlb-vs-alb': () => import('./nlb-vs-alb/config'),
  'serverless-api': () => import('./serverless-api/config'),
  'event-driven': () => import('./event-driven/config'),
  'llm-rag': () => import('./llm-rag/config'),
};

export const topicManifest: TopicManifest[] = [
  {
    slug: 'network-simulation',
    title: 'IP変換(NAT)とルーティング',
    description: 'AWS VPCにおけるパケットの流れと、NAT・ルーティングの仕組みを視覚的に学習',
    icon: 'Network',
    color: 'blue',
    badge: 'インタラクティブ',
    path: '/topics/network-simulation',
  },
  {
    slug: 'prod-architecture',
    title: '本番Webアプリ構成の通信フロー',
    description: 'CloudFront・S3・ALB・ECS Fargate・RDSによる本番構成で、画面表示・API通信・デプロイの通信がどう流れるかを視覚的に学習',
    icon: 'Server',
    color: 'blue',
    badge: 'インタラクティブ',
    path: '/topics/prod-architecture',
  },
  {
    slug: 'security-groups',
    title: 'Security Group 設計',
    description: 'ALB→ECS→RDSのSGチェーンを、通信が「許可される/遮断される」流れで理解する',
    icon: 'Shield',
    color: 'rose',
    badge: 'インタラクティブ',
    path: '/topics/security-groups',
  },
  {
    slug: 'ssm-port-forwarding',
    title: 'SSMでPrivate RDSへ接続',
    description: 'RDSをpublicにせず、SSHも開けずに、SSMポートフォワーディングで安全にDB接続する流れ',
    icon: 'PlugZap',
    color: 'amber',
    badge: 'インタラクティブ',
    path: '/topics/ssm-port-forwarding',
  },
  {
    slug: 'secrets-injection',
    title: 'Secrets注入とECS起動',
    description: '秘密をコードに書かずにSecrets Manager/SSMからECS Taskへ注入する流れと失敗パターン',
    icon: 'KeyRound',
    color: 'rose',
    badge: 'インタラクティブ',
    path: '/topics/secrets-injection',
  },
  {
    slug: 'egress-nat-vs-vpce',
    title: 'NAT vs VPCエンドポイント',
    description: 'Private Subnetからの外向き通信を、外部API向けのNATとAWSサービス向けのVPC Endpointで比較',
    icon: 'Plug',
    color: 'amber',
    badge: 'インタラクティブ',
    path: '/topics/egress-nat-vs-vpce',
  },
  {
    slug: 'multi-az-failover',
    title: 'Multi-AZ とフェイルオーバー',
    description: '2AZにALB・ECS・RDSを分散する構成で、平常時の流れとAZ障害時のfailoverを見る',
    icon: 'Network',
    color: 'blue',
    badge: 'インタラクティブ',
    path: '/topics/multi-az-failover',
  },
  {
    slug: 'ecs-scaling',
    title: 'ECS Auto Scaling の動き',
    description: '負荷に応じてECS FargateのTask数が増減する仕組みを、CloudWatch→Auto Scaling→Desired Countの流れで見る',
    icon: 'Gauge',
    color: 'blue',
    badge: 'インタラクティブ',
    path: '/topics/ecs-scaling',
  },
  {
    slug: 'nlb-vs-alb',
    title: 'NLB と ALB（L4 と L7）',
    description: '同じリクエストがALB(L7)とNLB(L4)でどう扱われるかを比較し、パスルーティング・送信元IP・固定IPの違いを理解する',
    icon: 'Network',
    color: 'blue',
    badge: 'インタラクティブ',
    path: '/topics/nlb-vs-alb',
  },
  {
    slug: 'serverless-api',
    title: 'サーバーレスAPI (API Gateway + Lambda)',
    description: 'API Gateway→Lambda→DynamoDBのリクエストの流れと、コールドスタート・同時実行・VPC接続の勘所を学ぶ',
    icon: 'Zap',
    color: 'amber',
    badge: 'インタラクティブ',
    path: '/topics/serverless-api',
  },
  {
    slug: 'event-driven',
    title: 'イベント駆動 (S3 / SQS → Lambda)',
    description: '保存やキュー投入をトリガに処理を非同期化する。リトライ・DLQ・冪等性まで疎結合な処理の流れを学ぶ',
    icon: 'Workflow',
    color: 'rose',
    badge: 'インタラクティブ',
    path: '/topics/event-driven',
  },
  {
    slug: 'llm-rag',
    title: 'LLM / RAG (Bedrock + OpenSearch)',
    description: '質問→埋め込み→ベクトル検索→根拠付き生成というRAGの流れと、取り込み・Guardrails・コストの勘所を学ぶ',
    icon: 'Brain',
    color: 'amber',
    badge: 'インタラクティブ',
    path: '/topics/llm-rag',
  },
  {
    slug: 'ecs-autoscaling',
    title: 'ECS Fargate と Auto Scaling',
    description: 'Cluster/Task Definition/Task/Service の関係と、Task数を増減するAuto Scalingの仕組みを図解',
    icon: 'Gauge',
    color: 'blue',
    badge: '図解ガイド',
    path: '/guides/ecs-autoscaling',
    kind: 'guide',
  },
  {
    slug: 'rds-multiaz-vs-replica',
    title: 'RDS Multi-AZ と Read Replica',
    description: '高可用性(Multi-AZ)と読み取り負荷分散(Read Replica)の違いを比較で理解する',
    icon: 'Database',
    color: 'amber',
    badge: '図解ガイド',
    path: '/guides/rds-multiaz-vs-replica',
    kind: 'guide',
  },
  {
    slug: 'observability',
    title: '監視・ログ・アラーム',
    description: '各レイヤのログ/メトリクスと、本番で最低限作るアラーム、WAF/SG/認可の守備範囲を整理',
    icon: 'Activity',
    color: 'rose',
    badge: '図解ガイド',
    path: '/guides/observability',
    kind: 'guide',
  },
  {
    slug: 'troubleshooting',
    title: '障害時の切り分け',
    description: '症状から原因へ、経路を区間に分けてたどる切り分けの地図(決定木と早見表)',
    icon: 'Stethoscope',
    color: 'blue',
    badge: '図解ガイド',
    path: '/guides/troubleshooting',
    kind: 'guide',
  },
  {
    slug: 'cost',
    title: 'コスト観点',
    description: '常時課金されるリソースと固定費/変動費、dev/prodでのトレードオフ判断',
    icon: 'Wallet',
    color: 'amber',
    badge: '図解ガイド',
    path: '/guides/cost',
    kind: 'guide',
  },
  {
    slug: 'terraform-structure',
    title: 'Terraform 構成と作る順序',
    description: 'モジュール分割と、ネットワークからアプリまでの依存関係(作る順序)を図解',
    icon: 'Boxes',
    color: 'rose',
    badge: '図解ガイド',
    path: '/guides/terraform-structure',
    kind: 'guide',
  },
];

export async function loadTopicConfig(slug: string): Promise<TopicConfig> {
  const loader = topicLoaders[slug];
  if (!loader) throw new Error(`Unknown topic: ${slug}`);
  const module = await loader();
  return module.default;
}
