import type { ChallengeConfig } from '../../types/challenge';
import type { DiagramConfig, DiagramNode, DiagramZone } from '../../types/diagram';
import {
  ICON,
  makeNode,
  makeServiceFactory,
  makeZone,
  makeZoneServiceFactory,
  nodeStyle,
  pickNodes,
} from '../shared';

const zones: DiagramZone[] = [
  makeZone('vpc', 'VPC (Document Search)', { x: 230, y: 150, width: 800, height: 540 }),
  makeZone('public-subnet', 'Public Subnet', { x: 24, y: 58, width: 340, height: 450 }, 'public', 'vpc'),
  makeZone('private-subnet', 'Private Subnet', { x: 398, y: 58, width: 360, height: 450 }, 'private', 'vpc'),
];

const answerNodes: DiagramNode[] = [
  makeNode('user-pc', '社内ユーザー', 'ブラウザ', 'Users', { x: 20, y: 345, width: 145, height: 86 }, nodeStyle.external, { category: 'external' }),
  makeNode('cognito', 'Cognito', '社内ログイン', 'LockKeyhole', { x: 220, y: 20, width: 150, height: 78 }, nodeStyle.security, { category: 'external' }),
  makeNode('cloudfront', 'CloudFront', '検索画面', ICON.cloudfront, { x: 410, y: 20, width: 165, height: 84 }, nodeStyle.edge, { category: 'external' }),
  makeNode('document-bucket', 'S3 Document Bucket', 'PDF/社内文書', ICON.s3, { x: 610, y: 20, width: 175, height: 84 }, nodeStyle.data, { category: 'external' }),
  makeNode('bedrock-embed', 'Bedrock Embeddings', 'ベクトル化', 'BrainCircuit', { x: 825, y: 20, width: 175, height: 84 }, nodeStyle.worker, { category: 'external' }),
  makeNode('bedrock-llm', 'Bedrock LLM', '根拠付き回答', 'Brain', { x: 1040, y: 20, width: 160, height: 84 }, nodeStyle.queue, { category: 'external' }),
  makeNode('guardrails', 'Guardrails', '出力制御', 'ShieldCheck', { x: 1040, y: 160, width: 160, height: 78 }, nodeStyle.security, { category: 'external' }),
  makeNode('ingest-queue', 'SQS Ingest Queue', '取り込み待ち', 'ListTodo', { x: 1040, y: 300, width: 170, height: 78 }, nodeStyle.queue, { category: 'external' }),
  makeNode('cloudwatch', 'CloudWatch Logs', '検索/取り込みログ', 'Activity', { x: 1040, y: 500, width: 175, height: 78 }, nodeStyle.observability, { category: 'external' }),
  makeNode('igw', 'Internet Gateway', 'VPC境界', ICON.igw, { x: 310, y: -32, width: 180, height: 78 }, nodeStyle.gateway, { category: 'gateway', parentId: 'zone-vpc' }),
  makeNode('alb', 'ALB', '検索API入口', ICON.alb, { x: 70, y: 160, width: 165, height: 84 }, nodeStyle.edge, { category: 'placement', parentId: 'zone-public-subnet' }),
  makeNode('ecs-search', 'ECS Fargate', '検索API', ICON.ecs, { x: 55, y: 72, width: 180, height: 84 }, nodeStyle.app, { category: 'placement', parentId: 'zone-private-subnet' }),
  makeNode('ecs-ingest', 'ECS Fargate', '取り込みWorker', ICON.ecs, { x: 55, y: 196, width: 180, height: 84 }, nodeStyle.worker, { category: 'placement', parentId: 'zone-private-subnet' }),
  makeNode('opensearch', 'OpenSearch', 'ベクトル検索', 'Search', { x: 55, y: 320, width: 180, height: 84 }, nodeStyle.data, { category: 'placement', parentId: 'zone-private-subnet' }),
  makeNode('public-rt', 'Public Route Table', '0.0.0.0/0 -> IGW', ICON.routeTable, { x: 145, y: 26, width: 175, height: 34 }, nodeStyle.routeTable, { category: 'association', parentId: 'zone-public-subnet' }),
  makeNode('private-rt', 'Private Route Table', 'local / endpoints', ICON.routeTable, { x: 165, y: 26, width: 175, height: 34 }, nodeStyle.routeTable, { category: 'association', parentId: 'zone-private-subnet' }),
  makeNode('sg-alb', 'SG: ALB', 'inbound 443', 'Shield', { x: 28, y: -22, width: 118, height: 30 }, nodeStyle.security, { category: 'association', parentId: 'alb' }),
  makeNode('sg-search', 'SG: Search ECS', 'from ALB SG', 'Shield', { x: 28, y: -22, width: 138, height: 30 }, nodeStyle.security, { category: 'association', parentId: 'ecs-search' }),
  makeNode('sg-ingest', 'SG: Ingest ECS', 'egress AWS svc', 'Shield', { x: 28, y: -22, width: 138, height: 30 }, nodeStyle.security, { category: 'association', parentId: 'ecs-ingest' }),
  makeNode('sg-opensearch', 'SG: OpenSearch', 'from ECS SG', 'Shield', { x: 28, y: -22, width: 146, height: 30 }, nodeStyle.security, { category: 'association', parentId: 'opensearch' }),
];

const createService = makeServiceFactory(answerNodes);
const createZoneService = makeZoneServiceFactory(zones);

const answerDiagram: DiagramConfig = {
  viewport: { width: 1260, height: 740, padding: 48 },
  zones,
  nodes: answerNodes,
  connections: [
    { id: 'user-to-cf', from: 'user-pc', to: 'cloudfront', kind: 'traffic', fromAnchor: 'top', toAnchor: 'left' },
    { id: 'cf-to-cognito', from: 'cloudfront', to: 'cognito', kind: 'traffic', fromAnchor: 'left', toAnchor: 'right' },
    { id: 'cf-to-igw', from: 'cloudfront', to: 'igw', kind: 'traffic', fromAnchor: 'bottom', toAnchor: 'top' },
    { id: 'igw-to-alb', from: 'igw', to: 'alb', kind: 'traffic', fromAnchor: 'bottom', toAnchor: 'top' },
    { id: 'alb-to-search', from: 'alb', to: 'ecs-search', kind: 'traffic', fromAnchor: 'right', toAnchor: 'left' },
    { id: 'search-to-docs', from: 'ecs-search', to: 'document-bucket', kind: 'traffic', fromAnchor: 'top', toAnchor: 'bottom' },
    { id: 'docs-to-queue', from: 'document-bucket', to: 'ingest-queue', kind: 'traffic', fromAnchor: 'right', toAnchor: 'top' },
    { id: 'queue-to-ingest', from: 'ingest-queue', to: 'ecs-ingest', kind: 'traffic', fromAnchor: 'left', toAnchor: 'right' },
    { id: 'ingest-to-embed', from: 'ecs-ingest', to: 'bedrock-embed', kind: 'traffic', fromAnchor: 'top', toAnchor: 'bottom' },
    { id: 'ingest-to-index', from: 'ecs-ingest', to: 'opensearch', kind: 'traffic', fromAnchor: 'bottom', toAnchor: 'top' },
    { id: 'search-to-index', from: 'ecs-search', to: 'opensearch', kind: 'traffic', fromAnchor: 'bottom', toAnchor: 'top' },
    { id: 'search-to-llm', from: 'ecs-search', to: 'bedrock-llm', kind: 'traffic', fromAnchor: 'top', toAnchor: 'bottom' },
    { id: 'llm-to-guardrails', from: 'bedrock-llm', to: 'guardrails', kind: 'traffic', fromAnchor: 'bottom', toAnchor: 'top' },
    { id: 'search-to-logs', from: 'ecs-search', to: 'cloudwatch', kind: 'traffic', fromAnchor: 'right', toAnchor: 'left' },
    { id: 'ingest-to-logs', from: 'ecs-ingest', to: 'cloudwatch', kind: 'traffic', fromAnchor: 'right', toAnchor: 'left' },
    { id: 'igw-to-public-rt', from: 'igw', to: 'public-rt', kind: 'attachment', label: 'route', fromAnchor: 'right', toAnchor: 'top' },
    { id: 'sg-alb-to-sg-search', from: 'sg-alb', to: 'sg-search', kind: 'association', label: '許可元', fromAnchor: 'right', toAnchor: 'left' },
    { id: 'sg-search-to-sg-opensearch', from: 'sg-search', to: 'sg-opensearch', kind: 'association', label: '許可元', fromAnchor: 'bottom', toAnchor: 'top' },
    { id: 'sg-ingest-to-sg-opensearch', from: 'sg-ingest', to: 'sg-opensearch', kind: 'association', label: '許可元', fromAnchor: 'bottom', toAnchor: 'right' },
  ],
};

const challenge: ChallengeConfig = {
  slug: 'document-search-app',
  title: 'ドキュメント検索アプリを設計する',
  description: 'ECS検索API、文書取り込みWorker、S3、SQS、Bedrock、OpenSearch、SGを含む検索アプリ構成を組み立てる',
  headerLabel: 'AWS DESIGN CHALLENGE',
  badge: '設計演習',
  icon: 'Search',
  color: 'amber',
  scenario:
    '社内ドキュメントをアップロードし、質問に対して根拠付きで回答する検索アプリを作ります。検索APIと取り込みWorkerはPrivate SubnetのECS Fargate、検索インデックスはVPC内OpenSearchとして配置し、Security Groupで通信元を絞った完成構成にしてください。',
  requirements: [
    { id: 'network', title: 'AWSネットワークの土台', description: 'VPC、Public/Private Subnet、Route Table、Internet Gatewayを明示する。' },
    { id: 'auth', title: '社内ユーザー認証', description: 'CloudFrontからCognitoへ連携し、社内ユーザーだけが使えるようにする。' },
    { id: 'search', title: '検索API', description: 'ALBだけをPublic Subnetに置き、検索APIはPrivate SubnetのECS Fargateで動かす。' },
    { id: 'upload', title: '文書アップロード', description: '検索APIからS3 Document Bucketへ文書を保存する。' },
    { id: 'ingest', title: '取り込み処理', description: 'S3イベントをSQSに積み、ECS WorkerがBedrock EmbeddingsとOpenSearchへ登録する。' },
    { id: 'answer', title: '根拠付き回答', description: 'ECS検索APIがOpenSearchで根拠を探し、Bedrock LLMとGuardrailsで回答する。' },
    { id: 'security', title: 'Security Group', description: 'ALB、ECS、OpenSearchにSGを関連付け、OpenSearchはECSからだけ許可する。' },
  ],
  initialDiagram: {
    viewport: { ...answerDiagram.viewport },
    zones: [],
    nodes: pickNodes(answerNodes, ['user-pc']),
    connections: [],
  },
  lockedNodeIds: ['user-pc'],
  services: [
    createZoneService('vpc', '検索アプリを動かすネットワーク境界'),
    createZoneService('public-subnet', 'ALBを置くSubnet'),
    createZoneService('private-subnet', 'ECSとOpenSearchを置くSubnet'),
    createService('cognito', '社内ユーザーのログイン基盤'),
    createService('cloudfront', '検索画面とAPIの公開入口'),
    createService('document-bucket', 'アップロード文書の保存先'),
    createService('bedrock-embed', '文書チャンクをベクトル化するBedrock'),
    createService('bedrock-llm', '回答生成を担うBedrock LLM'),
    createService('guardrails', '回答の出力制御'),
    createService('ingest-queue', '文書取り込みを非同期化するQueue'),
    createService('cloudwatch', '検索と取り込みのログ出力先'),
    createService('igw', 'VPCの外部接続点'),
    createService('alb', 'ECS検索APIへの公開受信口'),
    createService('ecs-search', '検索APIを動かすECS Fargate'),
    createService('ecs-ingest', '文書取り込みを行うECS Fargate'),
    createService('opensearch', 'VPC内のベクトル検索インデックス'),
    createService('public-rt', 'Public SubnetのRoute Table'),
    createService('private-rt', 'Private SubnetのRoute Table'),
    createService('sg-alb', 'ALBに関連付けるSG'),
    createService('sg-search', '検索APIに関連付けるSG'),
    createService('sg-ingest', '取り込みWorkerに関連付けるSG'),
    createService('sg-opensearch', 'OpenSearchに関連付けるSG'),
  ],
  awsRules: {
    vpcZoneId: 'vpc',
    publicSubnetZoneIds: ['public-subnet'],
    privateSubnetZoneIds: ['private-subnet'],
    internetGatewayNodeId: 'igw',
    routeTables: [
      { routeTableNodeId: 'public-rt', subnetZoneId: 'public-subnet', label: 'Public Route Table', requiresInternetGatewayConnection: { internetGatewayNodeId: 'igw' } },
      { routeTableNodeId: 'private-rt', subnetZoneId: 'private-subnet', label: 'Private Route Table' },
    ],
    securityGroups: [
      { securityGroupNodeId: 'sg-alb', attachedToNodeId: 'alb', label: 'ALB Security Group' },
      { securityGroupNodeId: 'sg-search', attachedToNodeId: 'ecs-search', label: 'Search ECS Security Group', allowedSourceSecurityGroupIds: ['sg-alb'] },
      { securityGroupNodeId: 'sg-ingest', attachedToNodeId: 'ecs-ingest', label: 'Ingest ECS Security Group' },
      { securityGroupNodeId: 'sg-opensearch', attachedToNodeId: 'opensearch', label: 'OpenSearch Security Group', allowedSourceSecurityGroupIds: ['sg-search', 'sg-ingest'] },
    ],
  },
  checks: [
    { id: 'auth-path', type: 'path-exists', path: ['user-pc', 'cloudfront', 'cognito'], label: '社内ユーザー認証を使える', failureMessage: '利用者がCloudFrontからCognitoへログインする流れが途切れています。' },
    { id: 'search-path', type: 'path-exists', path: ['user-pc', 'cloudfront', 'igw', 'alb', 'ecs-search'], label: '検索APIへ到達できる', failureMessage: '利用者の検索リクエストがPrivate SubnetのECS Fargateまで届く流れが途切れています。' },
    { id: 'upload-path', type: 'connection-exists', from: 'ecs-search', to: 'document-bucket', label: '文書をアップロードできる', failureMessage: 'ECS検索APIからS3 Document Bucketへ文書を保存する経路がありません。' },
    { id: 'ingest-path', type: 'path-exists', path: ['document-bucket', 'ingest-queue', 'ecs-ingest', 'opensearch'], label: '文書を検索可能にできる', failureMessage: '文書保存後にSQSとECS Workerを経由してOpenSearchへ登録する流れが途切れています。' },
    { id: 'embedding-path', type: 'connection-exists', from: 'ecs-ingest', to: 'bedrock-embed', label: 'Embeddingを作成できる', failureMessage: 'ECS取り込みWorkerからBedrock Embeddingsへの経路がありません。' },
    { id: 'answer-path', type: 'path-exists', path: ['ecs-search', 'opensearch', 'bedrock-llm', 'guardrails'], label: '根拠付き回答を生成できる', failureMessage: '検索APIからOpenSearch、Bedrock LLM、Guardrailsへ進む回答生成の流れが途切れています。' },
    { id: 'search-logs', type: 'connection-exists', from: 'ecs-search', to: 'cloudwatch', label: '検索APIログを出せる', failureMessage: 'ECS検索APIからCloudWatch Logsへのログ出力経路がありません。' },
    { id: 'ingest-logs', type: 'connection-exists', from: 'ecs-ingest', to: 'cloudwatch', label: '取り込みログを出せる', failureMessage: 'ECS取り込みWorkerからCloudWatch Logsへのログ出力経路がありません。' },
    { id: 'alb-public', type: 'node-in-zone', nodeId: 'alb', zoneId: 'public-subnet', label: 'ALBはPublic Subnetにある', failureMessage: 'ALBがPublic Subnetに配置されていません。' },
    { id: 'search-private', type: 'node-in-zone', nodeId: 'ecs-search', zoneId: 'private-subnet', label: '検索APIはPrivate Subnetにある', failureMessage: 'ECS Fargateの検索APIがPrivate Subnetに配置されていません。' },
    { id: 'ingest-private', type: 'node-in-zone', nodeId: 'ecs-ingest', zoneId: 'private-subnet', label: '取り込みWorkerはPrivate Subnetにある', failureMessage: 'ECS Fargateの取り込みWorkerがPrivate Subnetに配置されていません。' },
    { id: 'opensearch-private', type: 'node-in-zone', nodeId: 'opensearch', zoneId: 'private-subnet', label: 'OpenSearchはPrivate Subnetにある', failureMessage: 'OpenSearchがPrivate Subnetに配置されていません。' },
    { id: 'opensearch-only-ecs', type: 'incoming-only-from', nodeId: 'opensearch', allowedSourceIds: ['ecs-search', 'ecs-ingest'], label: 'OpenSearchはECSからだけ使う', failureMessage: 'OpenSearchへECS以外から入る経路があります。' },
  ],
  actions: [
    { id: 'login', title: '社内ユーザーがログインする', description: 'CloudFrontからCognitoでログインする。', checkIds: ['auth-path'], successMessage: '検索アプリは社内ユーザー認証を利用できます。', failureMessage: '認証構成の確認に失敗しました。' },
    { id: 'upload-doc', title: '文書をアップロードする', description: 'ECS検索APIがS3へ文書を保存する。', checkIds: ['search-path', 'upload-path', 'alb-public', 'search-private'], successMessage: '社内文書を検索対象として保存できます。', failureMessage: '文書アップロードの確認に失敗しました。' },
    { id: 'ingest-doc', title: '文書を検索可能にする', description: 'SQSとECS Workerで文書を取り込み、OpenSearchへ登録する。', checkIds: ['ingest-path', 'embedding-path', 'ingest-private', 'opensearch-private'], successMessage: '文書を取り込み、ベクトル検索の対象にできます。', failureMessage: '文書取り込みの確認に失敗しました。' },
    { id: 'ask', title: '質問に根拠付きで回答する', description: 'OpenSearchで根拠を検索し、Bedrock LLMで回答する。', checkIds: ['answer-path', 'opensearch-only-ecs'], successMessage: '検索結果を根拠に回答を生成し、出力制御を通せます。', failureMessage: '質問応答の確認に失敗しました。' },
    { id: 'operate', title: '検索と取り込みを運用する', description: 'ECS検索APIと取り込みWorkerのログを確認できる。', checkIds: ['search-logs', 'ingest-logs'], successMessage: '検索と取り込み処理のログを確認できます。', failureMessage: 'ログ確認の経路が不足しています。' },
  ],
  answerDiagram,
  answerTrace: [
    { id: 'network', title: '検索アプリのVPC土台を作る', description: 'ALBはPublic Subnet、ECS FargateとOpenSearchはPrivate Subnetに置く構成です。', visibleNodeIds: ['user-pc', 'igw', 'public-rt', 'private-rt'], visibleConnectionIds: ['igw-to-public-rt'], activeNodeIds: ['igw', 'public-rt', 'private-rt'], activeConnectionIds: ['igw-to-public-rt'] },
    { id: 'entry', title: '認証と検索API入口を作る', description: 'CloudFrontからCognitoへログインし、検索リクエストはIGW、ALB、ECS Fargateへ届きます。', visibleNodeIds: ['user-pc', 'cognito', 'cloudfront', 'igw', 'public-rt', 'private-rt', 'alb', 'sg-alb', 'ecs-search', 'sg-search'], visibleConnectionIds: ['user-to-cf', 'cf-to-cognito', 'cf-to-igw', 'igw-to-alb', 'alb-to-search', 'igw-to-public-rt', 'sg-alb-to-sg-search'], activeNodeIds: ['cloudfront', 'cognito', 'alb', 'ecs-search', 'sg-alb', 'sg-search'], activeConnectionIds: ['cf-to-cognito', 'cf-to-igw', 'igw-to-alb', 'alb-to-search', 'sg-alb-to-sg-search'] },
    { id: 'ingest', title: '文書を取り込んでOpenSearchへ登録する', description: 'アップロード文書をS3に保存し、SQS経由でECS WorkerがBedrock Embeddingsを使ってOpenSearchへ登録します。', visibleNodeIds: ['user-pc', 'cognito', 'cloudfront', 'document-bucket', 'bedrock-embed', 'ingest-queue', 'igw', 'public-rt', 'private-rt', 'alb', 'sg-alb', 'ecs-search', 'sg-search', 'ecs-ingest', 'sg-ingest', 'opensearch', 'sg-opensearch'], visibleConnectionIds: ['user-to-cf', 'cf-to-cognito', 'cf-to-igw', 'igw-to-alb', 'alb-to-search', 'search-to-docs', 'docs-to-queue', 'queue-to-ingest', 'ingest-to-embed', 'ingest-to-index', 'igw-to-public-rt', 'sg-alb-to-sg-search', 'sg-search-to-sg-opensearch', 'sg-ingest-to-sg-opensearch'], activeNodeIds: ['document-bucket', 'ingest-queue', 'ecs-ingest', 'bedrock-embed', 'opensearch', 'sg-opensearch'], activeConnectionIds: ['search-to-docs', 'docs-to-queue', 'queue-to-ingest', 'ingest-to-embed', 'ingest-to-index', 'sg-ingest-to-sg-opensearch'] },
    { id: 'query', title: '根拠付き回答を生成する', description: 'ECS検索APIがOpenSearchで根拠を探し、Bedrock LLMで回答を生成し、Guardrailsを通して返します。ログはCloudWatchへ出します。', visibleNodeIds: ['user-pc', 'cognito', 'cloudfront', 'document-bucket', 'bedrock-embed', 'bedrock-llm', 'guardrails', 'ingest-queue', 'cloudwatch', 'igw', 'public-rt', 'private-rt', 'alb', 'sg-alb', 'ecs-search', 'sg-search', 'ecs-ingest', 'sg-ingest', 'opensearch', 'sg-opensearch'], visibleConnectionIds: ['user-to-cf', 'cf-to-cognito', 'cf-to-igw', 'igw-to-alb', 'alb-to-search', 'search-to-docs', 'docs-to-queue', 'queue-to-ingest', 'ingest-to-embed', 'ingest-to-index', 'search-to-index', 'search-to-llm', 'llm-to-guardrails', 'search-to-logs', 'ingest-to-logs', 'igw-to-public-rt', 'sg-alb-to-sg-search', 'sg-search-to-sg-opensearch', 'sg-ingest-to-sg-opensearch'], activeNodeIds: ['ecs-search', 'opensearch', 'bedrock-llm', 'guardrails', 'cloudwatch'], activeConnectionIds: ['search-to-index', 'search-to-llm', 'llm-to-guardrails', 'search-to-logs', 'ingest-to-logs'] },
  ],
};

export default challenge;
